
//need to change direction based of direction I'm faceing 
//turnAround points to image in opposite array that switches current array and 
//array of images

let images = [

  //LOBBY
  //POSITION ONE
  {
      image:"images/lobby-1-F-1st.JPG", 
      forward:"images/lobby-3-F-1st.JPG", 
      backward:"images/lobby-1-B-1st.JPG", 
      left:"images/lobby-1-L-1st.JPG", 
      right:null,
   
  },


  {
      image:"images/lobby-1-B-1st.JPG",
      forward: null,
      backward:"images/lobby-1-F-1st.JPG",
      left:null, 
      right:"images/lobby-1-L-1st.JPG",
      turnAround:null
  },
  {
      image:"images/lobby-1-L-1st.JPG",
      forward:"images/lobby-2-F-1st.JPG", 
      backward:"images/lobby-1-F-1st.JPG", 
      left:null, 
      right:null,
      turnAround:null
  },   
  //LOBBY
  //POSITION TWO POSITION TWO POSITION TWO POSITION TWO POSITION TWO POSITION TWO
  {
      image:"images/lobby-2-F-1st.JPG", 
      forward:"first/cr-1-f.JPG", 
      backward:"images/lobby-2-B-1st.JPG", 
      left:null, 
      right:null,
      turnAround:null
  },     
  {
    image:"images/lobby-2-B-1st.JPG", 
    forward:null, 
    backward:"images/lobby-2-F-1st.JPG", 
    left:"images/lobby-2-L-1st.JPG", 
    right:"images/lobby-1-B-1st.JPG",
    turnAround:null
  },     
  {
    image:"images/lobby-2-L-1st.JPG", 
    forward:"images/lobby-3-F-1st.JPG", 
    backward:"images/lobby-2-B-1st.JPG", 
    left:null, 
    right:null,
    turnAround:null
  },     
  //LOBBY
  //POSITION THREE
  {
    image:"images/lobby-3-F-1st.JPG",
    forward:null, 
    backward:"images/lobby-3-B-1st.JPG", 
    left:"images/lobby-3-L-1st.JPG", 
    right:"images/lobby-3-R-1st.JPG",
    turnAround:null
  },   
  {
    image:"images/lobby-3-B-1st.JPG",
    forward:"images/lobby-1-B-1st.JPG", 
    backward:"images/lobby-3-F-1st.JPG", 
    left:null, 
    right:"images/lobby-2-F-1st.JPG",
    turnAround:null
  },   
  {
    image:"images/lobby-3-L-1st.JPG",
    forward:"images/lobby-4-F-1st.JPG", 
    backward:"images/lobby-3-F-1st.JPG", 
    left:"images/lobby-3-B-1st.JPG", 
    right:null,
    turnAround:null
  },   
  {
    image:"images/lobby-3-R-1st.JPG",
    forward:"images/100S-20-F.JPG", 
    backward:"images/lobby-33-F.JPG", 
    left:null, 
    right:"images/lobby-3-B-1st.JPG",
    turnAround:null
  }, 
  {
    image:"images/lobby-33-F.JPG", 
    forward:"images/lobby-3-L-1st.JPG", 
    backward:"images/lobby-3-R-1st.JPG", 
    left:"images/lobby-3-B-1st.JPG", 
    right:null
    },  
//LOBBY
//POSITION FOUR
{
  image:"images/lobby-4-F-1st.JPG",
  forward:"images/lobby-5-F-2nd.JPG", 
  backward:null, 
  left:null, 
  right:"images/lobby-S-R.JPG",
  turnAround:null
},   
{
  image:"images/lobby-S-R.JPG",
  forward:"images/lobby-3-R-1st.JPG", 
  backward:null, 
  left:"images/lobby-4-F-1st.JPG", 
  right:null,
  turnAround:null
},  
//LOBBY
//POSITION FIVE
{
  image:"images/lobby-5-F-2nd.JPG",
  forward:"images/200S-1-F.JPG", 
  backward:"images/lobby-5-B-2nd.JPG", 
  left:null, 
  right:null,
  turnAround:null
},   
{
  image:"images/lobby-5-B-2nd.JPG",
  forward:"images/lobby-4-F-1st.JPG", 
  backward:"images/lobby-5-F-2nd.JPG", 
  left:null, 
  right:null,
  turnAround:null
}, 
 {
  image:"images/100S-13-B.JPG", 
  forward:null, 
  backward:"images/100S-13-F.JPG", 
  left:"images/200S-12-F.JPG", 
  right:null
  },
  {
  image:"images/100S-13-F.JPG", 
  forward:"images/100S-14-F.JPG", 
  backward:"images/100S-13-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-14-F.JPG", 
  forward:"images/100S-15-F.JPG", 
  backward:"images/100S-15-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-15-B.JPG", 
  forward:"images/100S-13-B.JPG", 
  backward:"images/100S-15-F.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-15-B.JPG", 
  forward:null, 
  backward:"images/100S-15-F.JPG", 
  left:null, 
  right:null
  },
    {
  image:"images/100S-15-F.JPG", 
  forward:"images/100S-16-F.JPG", 
  backward:"images/100S-15-B.JPG", 
  left:null, 
  right:null
  },
   {
  image:"images/100S-16-F.JPG", 
  forward:"images/100S-17-F.JPG", 
  backward:"images/100S-16-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-16-B.JPG", 
  forward:"images/100S-33-F.JPG", 
  backward:"images/100S-16-F.JPG", 
  left:null, 
  right:null
   },
   {
  image:"images/100S-33-F.JPG", 
  forward:"images/100S-15-B.JPG", 
  backward:"images/100S-16-F.JPG", 
  left:null, 
  right:null
  },
   {
  image:"images/100S-17-F.JPG", 
  forward:"images/100S-18-F.JPG", 
  backward:"images/100S-16-B.JPG", 
  left:null, 
  right:null
  },
{
  image:"images/100S-18-F.JPG", 
  forward:"images/100S-19-F.JPG", 
  backward:"images/100S-18-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-18-B.JPG", 
  forward:"images/100S-16-B.JPG", 
  backward:"images/100S-18-F.JPG", 
  left:null, 
  right:null
  },


 {
 image:"images/100S-19-F.JPG", 
 forward:"images/lobby-33-F.JPG", 
 backward:"images/100S-19-B.JPG", 
 left:null, 
 right:null
  },
{
 image:"images/100S-19-B.JPG", 
 forward:"images/100S-18-B.JPG", 
 backward:"images/100S-19-F.JPG", 
 left:null, 
 right:null
},

  {
  image:"images/100S-13-F.JPG", 
  forward:"images/100S-14-F.JPG", 
  backward:"images/100S-13-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-14-F.JPG", 
  forward:"images/100S-15-F.JPG", 
  backward:"images/100S-15-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-15-B.JPG", 
  forward:"images/100S-13-B.JPG", 
  backward:"images/100S-15-F.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-15-B.JPG", 
  forward:null, 
  backward:"images/100S-15-F.JPG", 
  left:null, 
  right:null
  },
    {
  image:"images/100S-15-F.JPG", 
  forward:"images/100S-16-F.JPG", 
  backward:"images/100S-15-B.JPG", 
  left:null, 
  right:null
  },
   {
  image:"images/100S-16-F.JPG", 
  forward:"images/100S-17-F.JPG", 
  backward:"images/100S-16-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-16-B.JPG", 
  forward:"images/100S-33-F.JPG", 
  backward:"images/100S-16-F.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-33-F.JPG", 
  forward:"images/100S-15-B.JPG", 
  backward:"images/100S-16-F.JPG", 
  left:null, 
  right:null
  },
{
  image:"images/100S-17-F.JPG", 
  forward:"images/100S-18-F.JPG", 
  backward:"images/100S-16-B.JPG", 
  left:null, 
  right:null
  },
{
  image:"images/100S-18-F.JPG", 
  forward:"images/100S-19-F.JPG", 
  backward:"images/100S-18-B.JPG", 
  left:null, 
  right:null
  },
  {
  image:"images/100S-18-B.JPG", 
  forward:"images/100S-16-B.JPG", 
  backward:"images/100S-18-F.JPG", 
  left:null, 
  right:null
  },


 {
  image:"images/100S-19-F.JPG", 
  forward:"images/lobby-33-F.JPG", 
  backward:"images/100S-19-B.JPG", 
  left:null, 
  right:null
  },
{
  image:"images/100S-19-B.JPG", 
   forward:"images/100S-18-B.JPG", 
  backward:"images/100S-19-F.JPG", 
  left:null, 
  right:null
},
{
  image:"images/100S-20-F.JPG",
  forward:"images/100S-19-B.JPG", 
  backward:"images/lobby-33-F.JPG", 
  left:null, 
  right:null,
  turnAround:null
}, 

//SECOND FLOOR
{
  image:"images/200S-1-F.JPG",
  forward:"images/200S-2-F.JPG", 
  backward:"images/200S-1-B.JPG", 
  left:"images/200S-1-L.JPG", 
  right:"images/200S-1-R.JPG",
  turnAround:null
},
{
  image:"images/200S-1-B.JPG",
  forward:"images/lobby-5-B-2nd.JPG", 
  backward:"images/200S-1-F.JPG", 
  left:"images/200S-1-R.JPG", 
  right:"images/200S-1-L.JPG",
  turnAround:null
},

{
  image:"images/200S-1-L.JPG",
  forward:"images/200S-3-F.JPG", 
  backward:null, 
  left:"images/200S-1-B.JPG", 
  right:"images/200S-1-F.JPG",
  turnAround:null
},
{
  image:"images/200S-1-R.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-1-F.JPG", 
  right:"images/200S-1-B.JPG",
  turnAround:null
},
{
  image:"images/200S-2-F.JPG",
  forward:"images/200S-4-F.JPG", 
  backward:"images/200S-2-B.JPG", 
  left:"images/200S-2-L.JPG", 
  right:null,
  turnAround:null
},
{
  image:"images/200S-2-B.JPG",
  forward:"images/200S-1-B.JPG", 
  backward:"images/200S-2-F.JPG", 
  left:"images/200S-1-R.JPG", 
  right:"images/200S-2-L.JPG",
  turnAround:null
},
{
  image:"images/200S-2-L.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-2-B.JPG", 
  right:"images/200S-2-F.JPG",
  turnAround:null
},
{
  image:"images/200S-3-F.JPG",
  forward:null, 
  backward:"images/200S-3-B.JPG", 
  left:"images/200S-3-L.JPG", 
  right:null,
  turnAround:null
},
{
  image:"images/200S-3-L.JPG",
  forward:"second/2nd-1-f.JPEG", 
  backward:null, 
  left:"images/200S-3-B.JPG", 
  right:"images/200S-3-F.JPG",
  turnAround:null
},
{
  image:"images/200S-3-B.JPG",
  forward:"images/200S-1-F.JPG", 
  backward:"images/200S-3-F.JPG", 
  left:null, 
  right:"images/200S-3-L.JPG",
  turnAround:null
},
{
  image:"images/200S-4-F.JPG",
  forward:"images/200S-5-F.JPG", 
  backward:"images/200S-4-B.JPG", 
  left:"images/200S-4-L.JPG", 
  right:"images/200S-4-R.JPG",
  turnAround:null
},
{
  image:"images/200S-4-B.JPG",
  forward:"images/200S-2-B.JPG", 
  backward:null, 
  left:"images/200S-4-R.JPG", 
  right:"images/200S-4-L.JPG",
  turnAround:null
},
{
  image:"images/200S-4-L.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-5-F.JPG", 
  right:"images/200S-4-F.JPG",
  turnAround:null
},
{
  image:"images/200S-4-R.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-5-F.JPG", 
  right:"images/200S-4-B.JPG",
  turnAround:null
},
{
  image:"images/200S-5-F.JPG",
  forward:"images/200S-7-F.JPG", 
  backward:"images/200S-4-B.JPG", 
  left:"images/200S-6-L.JPG", 
  right:"images/200S-4-R.JPG",
  turnAround:null
},
{
  image:"images/200S-6-L.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-4-B.JPG", 
  right:"images/200S-5-F.JPG",
  turnAround:null
},
{
  image:"images/200S-7-B.JPG",
  forward:"images/200S-4-B.JPG", 
  backward:"images/200S-4-F.JPG", 
  left:null, 
  right:"images/200S-7-L.JPG",
  turnAround:null
},
{
  image:"images/200S-7-F.JPG",
  forward:"images/200S-8-F.JPG", 
  backward:"images/200S-7-B.JPG", 
  left:"images/200S-7-L.JPG", 
  right:null,
  turnAround:null
},
{
  image:"images/200S-7-L.JPG",
  forward:null, 
  backward:"images/200S-7-B.JPG", 
  left:"images/200S-7-B.JPG", 
  right:"images/200S-7-F.JPG",
  turnAround:null
},
// {
//   image:"images/200S-7-R.JPG",
//   forward:null, 
//   backward:"images/200S-7-B.JPG", 
//   left:"images/200S-7-F.JPG", 
//   right:"images/200S-7-B.JPG",
//   turnAround:null
// },
{
  image:"images/200S-8-F.JPG",
  forward:"images/200S-9-F.JPG", 
  backward:"images/200S-8-B.JPG", 
  left:"images/200S-8-L.JPG", 
  right:"images/200S-8-R.JPG",
},
{
  image:"images/200S-8-B.JPG",
  forward:"images/200S-7-B.JPG", 
  backward:"images/200S-8-F.JPG", 
  left:"images/200S-8-R.JPG", 
  right:"images/200S-8-L.JPG",
},
{
  image:"images/200S-8-L.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-8-B.JPG", 
  right:"images/200S-8-F.JPG",
},
{
  image:"images/200S-8-R.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-8-F.JPG", 
  right:"images/200S-8-B.JPG",
},
{
  image:"images/200S-9-F.JPG",
  forward:"images/200S-10-B.JPG", 
  backward:"images/200S-9-B.JPG", 
  left:"images/200S-9-L.JPG", 
  right:"images/200S-9-R.JPG",
},
{
  image:"images/200S-9-L.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-9-B.JPG", 
  right:"images/200S-9-F.JPG",
},
{
  image:"images/200S-9-R.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-9-F.JPG", 
  right:"images/200S-9-B.JPG",
},
{
  image:"images/200S-9-B.JPG",
  forward:"images/200S-8-B.JPG", 
  backward:"images/200S-10-B.JPG", 
  left:"images/200S-9-R.JPG", 
  right:"images/200S-9-L.JPG",
},
{
  image:"images/200S-10-B.JPG",
  forward:"images/200S-11-F.JPG", 
  backward:"images/200S-10-F.JPG", 
  left:null, 
  right:null,
},
{
  image:"images/200S-10-F.JPG",
  forward:"images/200S-9-B.JPG", 
  backward:"images/200S-10-B.JPG", 
  left:null, 
  right:null,
},
{
  image:"images/200S-11-F.JPG",
  forward:"images/200S-12-F.JPG", 
  backward:"images/200S-11-B.JPG", 
  left:null, 
  right:null,
},
{
  image:"images/200S-11-B.JPG",
  forward:"images/200S-10-F.JPG", 
  backward:"images/200S-11-F.JPG", 
  left:null, 
  right:null,
},
{
  image:"images/200S-12-F.JPG",
  forward:null, 
  backward:null, 
  left:"images/200S-12-R.JPG", 
  right:"images/200S-12-B.JPG",
},

{
  image:"images/200S-12-B.JPG",
  forward:"images/200S-11-B.JPG", 
  backward:"images/200S-12-F.JPG", 
  left:null, 
  right:"images/200S-12-R.JPG",
},
{
  image:"images/200S-12-R.JPG",
  forward:"images/100S-13-F.JPG", 
  backward:"images/200S-12-F.JPG", 
  left:"images/200S-12-B.JPG", 
  right:null,
},
{
  image:"images/200S-12-F.JPG",
  forward:"images/100S-13-F.JPG", 
  backward:"images/200S-12-B.JPG", 
  left:null, 
  right:null,
},

//couch room 
//first floor
{
  image:"first/cr-1-f.JPG", 
  forward:"first/cr-3-f.JPG", 
  backward:"first/cr-1-b.JPG", 
  left:null, 
  right:"first/cr-2-f.JPG",

},
{
  image:"first/cr-1-b.JPG", 
  forward:"images/lobby-2-B-1st.JPG", 
  backward:"first/cr-1-f.JPG", 
  left:null, 
  right:null,

},
{
  image:"first/cr-2-f.JPG", 
  forward:"first/f-1-f.JPG", 
  backward:"first/cr-2-b.JPG", 
  left:null, 
  right:null,

},
{
  image:"first/cr-2-b.JPG", 
  forward:null, 
  backward:"first/cr-2-f.JPG", 
  left:"first/cr-1-b.JPG", 
  right:"first/cr-3-f.JPG",

},
{
  image:"first/cr-3-f.JPG", 
  forward:"first/entrance-1-f.JPG", 
  backward:"first/cr-3-b.JPG", 
  left:null, 
  right:null,

},
{
  image:"first/cr-3-b.JPG", 
  forward:"first/cr-1-b.JPG", 
  backward:"first/cr-3-f.JPG", 
  left:"first/cr-2-f.JPG", 
  right:null,

},
{
  image:"first/entrance-1-f.JPG", 
  forward:null, 
  backward:"first/entrance-1-b.JPG", 
  left:"first/entrance-2-f.JPG", 
  right:"first/entrance-3-f.JPG",

},
{
  image:"first/entrance-1-b.JPG", 
  forward:"first/cr-3-b.JPG", 
  backward:"first/entrance-1-f.JPG", 
  left:"first/entrance-3-f.JPG", 
  right:"first/entrance-2-f.JPG",

},
{
  image:"first/entrance-2-f.JPG", 
  forward:"first/1-n-7-f.JPG", 
  backward:"first/entrance-2-b.JPG", 
  left:null, 
  right:"first/entrance-info.JPG",

},
{
  image:"first/entrance-2-b.JPG", 
  forward:"first/entrance-3-f.JPG", 
  backward:"first/entrance-2-f.JPG", 
  left:null, 
  right:"first/entrance-1-b.JPG",

},
{
  image:"first/entrance-info.JPG", 
  forward:null, 
  backward:"first/entrance-2-b.JPG", 
  left:"first/entrance-2-f.JPG", 
  right:null,

},
{
  image:"first/entrance-3-f.JPG", 
  forward:"first/1-n-1-f.JPG", 
  backward:"first/entrance-3-b.JPG", 
  left:null, 
  right:"first/entrance-1-b.JPG",

},
{
  image:"first/entrance-3-b.JPG", 
  forward:"first/entrance-2-f.JPG", 
  backward:"first/entrance-3-f.JPG", 
  left:"first/entrance-1-b.JPG", 
  right:"null",

},
{
  image:"first/1-n-1-f.JPG", 
  forward:"first/1-n-2-f.JPG", 
  backward:"first/1-n-1-b.JPG", 
  left:null, 
  right:null,

},
{
  image:"first/1-n-1-b.JPG", 
  forward:"first/entrance-3-b.JPG", 
  backward:"first/1-n-1-f.JPG", 
  left:null, 
  right:null,

},
{
  image:"first/1-n-2-f.JPG", 
  forward:"first/1-n-3-f.JPG", 
  backward:"first/1-n-2-b.JPG", 
  left:"first/1-n-2-l.JPG", 
  right:null,

},
{
  image:"first/1-n-2-b.JPG", 
  forward:"first/1-n-1-b.JPG", 
  backward:"first/1-n-2-f.JPG", 
  left:null, 
  right:"first/1-n-2-l.JPG",

},
{
  image:"first/1-n-2-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/1-n-2-b.JPG", 
  right:"first/1-n-2-f.JPG",

},
{
  image:"first/1-n-3-f.JPG", 
  forward:"first/1-n-4-f.JPG", 
  backward:"first/1-n-3-b.JPG", 
  left:"first/1-n-3-l.JPG", 
  right:"first/1-n-3-r.JPG",

},
{
  image:"first/1-n-3-b.JPG", 
  forward:"first/1-n-2-b.JPG", 
  backward:"first/1-n-3-f.JPG", 
  left:"first/1-n-3-r.JPG", 
  right:"first/1-n-3-l.JPG",

},
{
  image:"first/1-n-3-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/1-n-3-f.JPG", 
  right:"first/1-n-3-b.JPG",

},
{
  image:"first/1-n-3-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/1-n-3-b.JPG", 
  right:"first/1-n-3-f.JPG",

},

//starting to download photos from icloud instead of transferring from iphone
//icloud downloads as jpeg
//makes the images 1mb instead of 3. might be enought to host all pictures on github. 
{
  image:"first/1-n-4-f.JPG", 
  forward:"first/1-n-5-f.JPG", 
  backward:"first/1-n-4-b.JPG", 
  left:"first/1-n-4-l.jpeg", 
  right:"first/1-n-4-r.JPG",

},
{
  image:"first/1-n-4-b.JPG", 
  forward:"first/1-n-3-b.JPG", 
  backward:"first/1-n-4-f.JPG", 
  left:"first/1-n-4-r.JPG", 
  right:null,

},
{
  image:"first/1-n-4-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/1-n-4-f.JPG", 
  right:"first/1-n-4-b.JPG",
},
{
  image:"first/1-n-4-l.jpeg", 
  forward:null, 
  backward:null, 
  left:"first/1-n-4-b.JPG", 
  right:"first/1-n-4-f.JPG",
},
{
  image:"first/1-n-5-f.JPG", 
  forward:"first/1-n-6-f.JPG", 
  backward:"first/1-n-5-b.JPG", 
  left:"first/1-n-5-l.JPG", 
  right:null,
},
{
  image:"first/1-n-5-b.JPG", 
  forward:"first/1-n-4-b.JPG", 
  backward:"first/1-n-5-f.JPG", 
  left:null, 
  right:"first/1-n-5-l.JPG",
},
{
  image:"first/1-n-5-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/1-n-5-b.JPG", 
  right:"first/1-n-5-f.JPG",
},
{
  image:"first/1-n-6-b.jpeg", 
  forward:"first/1-n-5-b.JPG", 
  backward:"first/1-n-6-f.JPG", 
  left:"first/1-n-5-l.JPG", 
  right:"first/1-n-6-l.JPG",
},
{
  image:"first/1-n-6-f.JPG", 
  forward:"stairs/stairs-12-r.JPEG", 
  backward:"first/1-n-6-b.jpeg", 
  left:"first/1-n-6-l.JPG", 
  right:"first/1-n-6-r.JPG",
},
{
  image:"first/1-n-6-r.JPG", 
  forward:"first/f-11-b.JPG", 
  backward:"first/1-n-6-l.JPG", 
  left:"first/1-n-6-f.JPG", 
  right:"first/1-n-6-b.jpeg",
},
{
  image:"first/1-n-6-l.JPG", 
  forward:null, 
  backward:"first/1-n-6-r.JPG", 
  left:"first/1-n-6-b.jpeg", 
  right:"first/1-n-6-f.JPG",
},
{
  image:"first/1-n-7-f.JPG", 
  forward:"first/1-n-8-f.JPG", 
  backward:"first/1-n-7-b.JPG", 
  left:null, 
  right:"first/1-n-7-r.JPG",
},
{
  image:"first/1-n-7-b.JPG", 
  forward:"first/entrance-2-b.JPG", 
  backward:"first/1-n-7-f.JPG", 
  left:"first/1-n-6-f.JPG", 
  right:null,
},
{
  image:"first/1-n-7-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/1-n-7-f.JPG", 
  right:"first/1-n-7-b.JPG",
},
{
  image:"first/1-n-8-f.JPG", 
  forward:"first/1-n-9-f.JPG", 
  backward:"first/1-n-8-b.JPG", 
  left:null, 
  right:"first/1-n-7-b.JPG",
},
{
  image:"first/1-n-8-b.JPG", 
  forward:"first/1-n-7-b.JPG", 
  backward:"first/1-n-8-f.JPG", 
  left:"first/1-n-8-r.JPG", 
  right:null,
},
{
  image:"first/1-n-8-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/1-n-8-f.JPG", 
  right:"first/1-n-8-b.JPG",
},
{
  image:"first/1-n-9-f.JPG", 
  forward:"first/1-n-10-f.JPG", 
  backward:"first/1-n-9-b.JPG", 
  left:null, 
  right:null,
},
{
  image:"first/1-n-9-b.JPG", 
  forward:"first/1-n-8-b.JPG", 
  backward:"first/1-n-9-f.JPG", 
  left:null, 
  right:null,
},
{
  image:"first/1-n-10-f.JPG", 
  forward:"stairs/stairs-11-f.JPEG", 
  backward:"first/1-n-9-b.JPG", 
  left:null, 
  right:"first/1-n-10-r.JPG",
},
{
  image:"first/1-n-10-r.JPG", 
  forward:"stairs/stairs-9-r.JPEG", 
  backward:"first/1-n-9-b.JPG", 
  left:"first/1-n-10-f.JPG", 
  right:null,
},

//offices and mailroom
//first floor
{
  image:"first/f-1-f.JPG", 
  forward:"first/f-3-f.JPG", 
  backward:"first/f-1-b.JPG", 
  left:"first/f-2-f.JPG", 
  right:null,
},
{
  image:"first/f-1-b.JPG", 
  forward:"first/cr-2-b.JPG", 
  backward:"first/f-1-f.JPG", 
  left:null, 
  right:"first/f-2-f.JPG",
},
{
  image:"first/f-2-f.JPG", 
  forward:"stairs/stairs-1-f.JPEG", 
  backward:"first/f-2-b.JPG", 
  left:null, 
  right:null,
},
{
  image:"first/f-2-b.JPG", 
  forward:null, 
  backward:"first/f-2-f.JPG", 
  left:"first/f-3-f.JPG", 
  right:"first/f-1-b.JPG",
},
{
  image:"first/f-3-f.JPG", 
  forward:"first/f-4-f.JPG", 
  backward:"first/f-3-b.JPG", 
  left:"first/f-3-f.JPG", 
  right:"first/f-3-r.JPG",
},
{
  image:"first/f-3-b.JPG", 
  forward:"first/f-1-b.JPG", 
  backward:"first/f-3-f.JPG", 
  left:"first/f-3-f.JPG", 
  right:"first/f-2-f.JPG",
},
{
  image:"first/f-3-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-3-f.JPG", 
  right:"first/f-3-b.JPG",
},
{
  image:"first/f-4-f.JPG", 
  forward:"first/f-5-f.JPG", 
  backward:"first/f-4-b.JPG", 
  left:"first/f-4-l.JPG", 
  right:"first/f-4-r.JPG",
},
{
  image:"first/f-4-b.JPG", 
  forward:"first/f-3-b.JPG", 
  backward:"first/f-4-f.JPG", 
  left:"first/f-4-r.JPG", 
  right:"first/f-4-l.JPG",
},
{
  image:"first/f-4-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-4-f.JPG", 
  right:"first/f-4-b.JPG",
},
{
  image:"first/f-4-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-4-b.JPG", 
  right:"first/f-4-f.JPG",
},
{
  image:"first/f-5-f.JPG", 
  forward:"first/f-6-f.JPG", 
  backward:"first/f-5-b.JPG", 
  left:"first/f-5-l.JPG", 
  right:"first/f-5-r.JPG",
},
{
  image:"first/f-5-b.JPG", 
  forward:"first/f-4-b.JPG", 
  backward:"first/f-5-f.JPG", 
  left:"first/f-5-r.JPG", 
  right:"first/f-5-l.JPG",
},
{
  image:"first/f-5-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-5-b.JPG", 
  right:"first/f-5-f.JPG",
},
{
  image:"first/f-5-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-5-f.JPG", 
  right:"first/f-5-b.JPG",
},
{
  image:"first/f-6-f.JPG", 
  forward:"first/f-7-f.JPG", 
  backward:"first/f-6-b.JPG", 
  left:null, 
  right:"first/f-6-r.JPG",
},
{
  image:"first/f-6-b.JPG", 
  forward:"first/f-5-b.JPG", 
  backward:"first/f-6-f.JPG", 
  left:"first/f-6-r.JPG", 
  right:null,
},
{
  image:"first/f-6-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-6-f.JPG", 
  right:"first/f-6-b.JPG",
},
{
  image:"first/f-7-f.JPG", 
  forward:"first/f-8-f.JPG", 
  backward:"first/f-7-b.JPG", 
  left:"first/f-7-l.JPG", 
  right:"first/f-7-r.JPG",
},
{
  image:"first/f-7-b.JPG", 
  forward:"first/f-6-b.JPG", 
  backward:"first/f-7-f.JPG", 
  left:"first/f-7-r.JPG", 
  right:"first/f-7-l.JPG",
},
{
  image:"first/f-7-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-7-b.JPG", 
  right:"first/f-7-f.JPG",
},
{
  image:"first/f-7-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-7-f.JPG", 
  right:"first/f-7-b.JPG",
},
{
  image:"first/f-8-f.JPG", 
  forward:"first/f-9-f.JPG", 
  backward:"first/f-8-b.JPG", 
  left:null, 
  right:"first/f-8-r.JPG",
},
{
  image:"first/f-8-b.JPG", 
  forward:"first/f-7-b.JPG", 
  backward:"first/f-8-f.JPG", 
  left:null, 
  right:null,
},
{
  image:"first/f-8-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-8-f.JPG", 
  right:"first/f-8-b.JPG",
},
{
  image:"first/f-9-f.JPG", 
  forward:"first/f-12-f.JPG", 
  backward:"first/f-9-b.JPG", 
  left:"first/f-105-f.JPG", 
  right:null,
},
{
  image:"first/f-9-b.JPG", 
  forward:"first/f-8-b.JPG", 
  backward:"first/f-9-f.JPG", 
  left:null, 
  right:"first/f-105-f.JPG",
},
{
  image:"first/f-12-f.JPG", 
  forward:"first/f-13-f.JPG", 
  backward:"first/f-12-b.JPG", 
  left:null, 
  right:"first/f-12-r.JPG",
},
{
  image:"first/f-12-b.JPG", 
  forward:"first/f-9-b.JPG", 
  backward:"first/f-12-f.JPG", 
  left:"first/f-12-r.JPG", 
  right:"first/f-12-l.JPG",
},
{
  image:"first/f-12-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-12-f.JPG", 
  right:"first/f-12-b.JPG",
},
{
  image:"first/f-13-f.JPG", 
  forward:"first/f-14-f.JPG", 
  backward:"first/f-13-b.JPG", 
  left:"first/f-13-l.JPG", 
  right:"first/f-13-r.JPG",
},
{
  image:"first/f-13-b.JPG", 
  forward:"first/f-12-b.JPG", 
  backward:"first/f-13-f.JPG", 
  left:"first/f-13-r.JPG", 
  right:"first/f-13-l.JPG",
},
{
  image:"first/f-13-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-13-f.JPG", 
  right:"first/f-13-b.JPG",
},
{
  image:"first/f-13-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-13-b.JPG", 
  right:"first/f-13-f.JPG",
},
{
  image:"first/f-14-f.JPG", 
  forward:null, 
  backward:"first/f-14-b.JPG", 
  left:"first/f-14-l.JPG", 
  right:"first/f-14-r.JPG",
},
{
  image:"first/f-14-b.JPG", 
  forward:"first/f-12-b.JPG", 
  backward:"first/f-14-f.JPG", 
  left:"first/f-14-r.JPG", 
  right:"first/f-14-l.JPG",
},
{
  image:"first/f-14-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-14-b.JPG", 
  right:"first/f-14-f.JPG",
},
{
  image:"first/f-14-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-14-f.JPG", 
  right:"first/f-14-b.JPG",
},
{
  image:"first/f-105-f.JPG", 
  forward:"first/f-10-f.JPG", 
  backward:"first/f-105-b.jpeg", 
  left:"first/f-9-b.JPG", 
  right:"first/f-9-f.JPG",
},
{
  image:"first/f-105-b.jpeg", 
  forward:null, 
  backward:"first/f-105-f.JPG", 
  left:"first/f-9-f.JPG", 
  right:"first/f-9-b.JPG",
},
{
  image:"first/f-10-f.JPG", 
  forward:"first/f-11-f.JPG", 
  backward:"first/f-10-b.JPG", 
  left:"first/f-10-l.JPG", 
  right:"first/f-10-r.JPG",
},
{
  image:"first/f-10-b.JPG", 
  forward:"first/f-105-b.jpeg", 
  backward:"first/f-10-f.JPG", 
  left:"first/f-10-r.JPG", 
  right:"first/f-10-l.JPG",
},
{
  image:"first/f-10-r.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-10-f.JPG", 
  right:"first/f-10-b.JPG",
},
{
  image:"first/f-10-l.JPG", 
  forward:null, 
  backward:null, 
  left:"first/f-10-b.JPG", 
  right:"first/f-10-f.JPG",
},
{
  image:"first/f-11-f.JPG", 
  forward:"first/1-n-6-l.JPG", 
  backward:"first/f-11-b.JPG", 
  left:null, 
  right:null,
},
{
  image:"first/f-11-b.JPG", 
  forward:"first/f-10-b.JPG", 
  backward:"first/f-11-f.JPG", 
  left:null, 
  right:null,
},
{
  image:"first/f-11-b.JPG", 
  forward:"first/f-10-b.JPG", 
  backward:"first/f-11-f.JPG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-1-f.JPEG", 
  forward:"second/2nd-2-f.JPEG", 
  backward:"second/2nd-1-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-1-b.JPEG", 
  forward:"images/200S-3-B.JPG", 
  backward:"second/2nd-1-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-2-f.JPEG", 
  forward:"second/2nd-3-l.JPEG", 
  backward:"second/2nd-2-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-2-b.JPEG", 
  forward:"second/2nd-1-b.JPEG", 
  backward:"second/2nd-2-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-3-l.JPEG", 
  forward:"stairs/stairs-3-r.JPEG", 
  backward:"second/2nd-3-r.JPEG", 
  left:null, 
  right:"second/2nd-3-f.JPEG",
},
{
  image:"second/2nd-3-r.JPEG", 
  forward:"second/2nd-2-b.JPEG", 
  backward:"second/2nd-3-l.JPEG", 
  left:"second/2nd-3-f.JPEG", 
  right:null,
},
{
  image:"second/2nd-3-f.JPEG", 
  forward:"second/2nd-20-b.JPEG", 
  backward:"second/2nd-3-b.JPEG", 
  left:"second/2nd-3-l.JPEG", 
  right:"second/2nd-3-r.JPEG",
},
{
  image:"second/2nd-3-b.JPEG", 
  forward:null, 
  backward:"second/2nd-3-f.JPEG", 
  left:"second/2nd-3-r.JPEG", 
  right:"second/2nd-3-l.JPEG",
},

{
  image:"stairs/stairs-1-f.JPEG", 
  forward:"stairs/stairs-2-l.JPEG", 
  backward:"stairs/stairs-1-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-1-b.JPEG", 
  forward:"first/f-2-b.JPG", 
  backward:"stairs/stairs-1-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-2-r.JPEG", 
  forward:"stairs/stairs-1-b.JPEG", 
  backward:null, 
  left:"stairs/stairs-2-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-2-l.JPEG", 
  forward:"stairs/stairs-3-f.JPEG", 
  backward:null, 
  left:null, 
  right:"stairs/stairs-2-r.JPEG",
},
{
  image:"stairs/stairs-3-f.JPEG", 
  forward:"second/2nd-3-r.JPEG", 
  backward:null, 
  left:"stairs/stairs-3-r.JPEG", 
  right:"stairs/stairs-3-l.JPEG",
},
{
  image:"stairs/stairs-3-l.JPEG", 
  forward:"stairs/stairs-4-l.JPEG", 
  backward:"stairs/stairs-3-f.JPEG", 
  left:null, 
  right:"stairs/stairs-3-r.JPEG",
},
{
  image:"stairs/stairs-3-r.JPEG", 
  forward:"stairs/stairs-2-r.JPEG", 
  backward:"stairs/stairs-3-f.JPEG", 
  left:"stairs/stairs-3-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-4-l.JPEG", 
  forward:"stairs/stairs-5-f.JPEG", 
  backward:null, 
  left:null, 
  right:"stairs/stairs-4-r.JPEG",
},
{
  image:"stairs/stairs-4-r.JPEG", 
  forward:"stairs/stairs-3-f.JPEG", 
  backward:null, 
  left:"stairs/stairs-4-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-5-f.JPEG", 
  forward:"third/3rd-1-f.JPEG",
  backward:"stairs/stairs-5-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-5-b.JPEG", 
  forward:"stairs/stairs-4-r.JPEG", 
  backward:"stairs/stairs-5-f.JPEG", 
  left:null, 
  right:null,
},

//north stairs facing moore center
{
  image:"stairs/stairs-6-f.JPEG", 
  forward:"stairs/stairs-7-f.JPEG", 
  backward:"stairs/stairs-6-b.JPEG", 
  left:null, 
  right:null,
},




{
  image:"third/3rd-1-f.JPEG", 
  forward:"third/3rd-2-f.JPEG", 
  backward:"third/3rd-1-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"third/3rd-1-b.JPEG", 
  forward:"stairs/stairs-5-b.JPEG", 
  backward:"third/3rd-1-f.JPEG", 
  left:null, 
  right:null,
},



{
  image:"third/3rd-2-f.JPEG", 
  forward:null, 
  backward:"third/3rd-2-b.JPEG", 
  left:"third/3rd-3-f.JPEG", 
  right:null,
},
{
  image:"third/3rd-2-b.JPEG", 
  forward:"third/3rd-1-b.JPEG", 
  backward:"third/3rd-2-f.JPEG", 
  left:null, 
  right:"third/3rd-3-f.JPEG",
},
{
  image:"third/3rd-3-f.JPEG", 
  forward:"third/3rd-4-f.JPEG", 
  backward:"third/3rd-3-b.JPEG", 
  left:"third/3rd-3-l.JPEG", 
  right:null,
},
{
  image:"third/3rd-3-b.JPEG", 
  forward:"third/3rd-2-b.JPEG", 
  backward:"third/3rd-3-f.JPEG", 
  left:"third/3rd-2-f.JPEG", 
  right:"third/3rd-3-l.JPEG",
},
{
  image:"third/3rd-3-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-3-b.JPEG", 
  right:"third/3rd-3-f.JPEG",
},
{
  image:"third/3rd-4-f.JPEG", 
  forward:"third/3rd-5-f.JPEG", 
  backward:"third/3rd-4-b.JPEG", 
  left:"third/3rd-4-l.JPEG", 
  right:"third/3rd-4-r.JPEG",
},
{
  image:"third/3rd-4-b.JPEG", 
  forward:"third/3rd-3-b.JPEG", 
  backward:"third/3rd-4-f.JPEG", 
  left:"third/3rd-4-r.JPEG", 
  right:"third/3rd-4-l.JPEG",
},
{
  image:"third/3rd-4-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-4-f.JPEG", 
  right:"third/3rd-4-b.JPEG",
},
{
  image:"third/3rd-4-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-4-b.JPEG", 
  right:"third/3rd-4-f.JPEG",
},
{
  image:"third/3rd-5-f.JPEG", 
  forward:"third/3rd-6-f.JPEG", 
  backward:"third/3rd-5-b.JPEG", 
  left:null, 
  right:"third/3rd-5-r.JPEG",
},
{
  image:"third/3rd-5-b.JPEG", 
  forward:"third/3rd-4-b.JPEG", 
  backward:"third/3rd-5-f.JPEG", 
  left:"third/3rd-5-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-5-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-5-f.JPEG", 
  right:"third/3rd-5-b.JPEG",
},

{
  image:"third/3rd-6-f.JPEG", 
  forward:"third/3rd-7-f.JPEG", 
  backward:"third/3rd-6-b.JPEG", 
  left:"third/3rd-6-l.JPEG", 
  right:"third/3rd-6-r.JPEG",
},

{
  image:"third/3rd-6-b.JPEG", 
  forward:"third/3rd-5-b.JPEG", 
  backward:"third/3rd-6-f.JPEG", 
  left:"third/3rd-6-r.JPEG", 
  right:"third/3rd-6-l.JPEG",
},
{
  image:"third/3rd-6-l.JPEG", 
  forward:"third/3rd-10-f.JPEG", 
  backward:"third/3rd-6-r.JPEG", 
  left:"third/3rd-6-b.JPEG", 
  right:"third/3rd-6-f.JPEG",
},
{
  image:"third/3rd-6-r.JPEG", 
  forward:null, 
  backward:"third/3rd-6-l.JPEG", 
  left:"third/3rd-6-f.JPEG", 
  right:"third/3rd-6-b.JPEG",
},
{
  image:"third/3rd-7-f.JPEG", 
  forward:"third/3rd-8-f.JPEG", 
  backward:"third/3rd-7-b.JPEG", 
  left:null, 
  right:"third/3rd-7-r.JPEG",
},
{
  image:"third/3rd-7-b.JPEG", 
  forward:"third/3rd-6-b.JPEG", 
  backward:"third/3rd-7-f.JPEG", 
  left:"third/3rd-7-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-7-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-7-f.JPEG", 
  right:"third/3rd-7-b.JPEG",
},
{
  image:"third/3rd-8-f.JPEG", 
  forward:"third/3rd-9-f.JPEG", 
  backward:"third/3rd-8-b.JPEG", 
  left:null, 
  right:"third/3rd-8-r.JPEG",
},
{
  image:"third/3rd-8-b.JPEG", 
  forward:"third/3rd-7-b.JPEG", 
  backward:"third/3rd-8-f.JPEG", 
  left:"third/3rd-8-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-8-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-8-f.JPEG", 
  right:"third/3rd-8-b.JPEG",
},
{
  image:"third/3rd-9-f.JPEG", 
  forward:null, 
  backward:"third/3rd-8-b.JPEG", 
  left:"third/3rd-9-l.JPEG", 
  right:"third/3rd-8-r.JPEG",
},

{
  image:"third/3rd-9-r.JPEG", 
  forward:null, 
  backward:"third/3rd-9-l.JPEG", 
  left:"third/3rd-9-f.JPEG", 
  right:"third/3rd-8-b.JPEG",
},
{
  image:"third/3rd-9-l.JPEG", 
  forward:null, 
  backward:"third/3rd-9-r.JPEG", 
  left:"third/3rd-8-b.JPEG", 
  right:"third/3rd-9-f.JPEG",
},
{
  image:"third/3rd-10-f.JPEG", 
  forward:"third/3rd-11-f.JPEG", 
  backward:"third/3rd-10-b.JPEG", 
  left:"third/3rd-10-l.JPEG", 
  right:"third/3rd-10-r.JPEG",
},
{
  image:"third/3rd-10-b.JPEG", 
  forward:"third/3rd-6-r.JPEG", 
  backward:"third/3rd-10-f.JPEG", 
  left:"third/3rd-10-r.JPEG", 
  right:"third/3rd-10-l.JPEG",
},
{
  image:"third/3rd-10-l.JPEG", 
  forward:null, 
  backward:"third/3rd-10-r.JPEG", 
  left:"third/3rd-10-b.JPEG", 
  right:"third/3rd-10-f.JPEG",
},
{
  image:"third/3rd-10-r.JPEG", 
  forward:null, 
  backward:"third/3rd-10-l.JPEG", 
  left:"third/3rd-10-f.JPEG", 
  right:"third/3rd-10-b.JPEG",
},
{
  image:"third/3rd-11-f.JPEG", 
  forward:"third/3rd-12-r.JPEG", 
  backward:"third/3rd-11-b.JPEG", 
  left:"third/3rd-11-l.JPEG", 
  right:null,
},
{
  image:"third/3rd-11-b.JPEG", 
  forward:"third/3rd-10-b.JPEG", 
  backward:"third/3rd-11-f.JPEG", 
  left:null, 
  right:"third/3rd-11-l.JPEG",
},
{
  image:"third/3rd-11-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-11-b.JPEG", 
  right:"third/3rd-11-f.JPEG",
},
{
  image:"third/3rd-12-r.JPEG", 
  forward:null, 
  backward:"third/3rd-12-l.JPEG", 
  left:"third/3rd-12-f.JPEG", 
  right:"third/3rd-12-b.JPEG",
},
{
  image:"third/3rd-12-f.JPEG", 
  forward:"third/3rd-13-f.JPEG", 
  backward:"third/3rd-12-b.JPEG", 
  left:"third/3rd-12-l.JPEG", 
  right:"third/3rd-12-r.JPEG",
},
{
  image:"third/3rd-12-b.JPEG", 
  forward:"stairs/stairs-17-b.JPEG", 
  backward:"third/3rd-12-f.JPEG", 
  left:"third/3rd-12-r.JPEG", 
  right:"third/3rd-12-l.JPEG",
},
{
  image:"third/3rd-12-l.JPEG", 
  forward:"third/3rd-11-b.JPEG", 
  backward:"third/3rd-12-r.JPEG", 
  left:"third/3rd-12-b.JPEG", 
  right:"third/3rd-12-f.JPEG",
},
{
  image:"third/3rd-13-f.JPEG", 
  forward:"third/3rd-14-f.JPEG", 
  backward:"third/3rd-13-b.JPEG", 
  left:null, 
  right:"third/3rd-13-r.JPEG",
},
{
  image:"third/3rd-13-b.JPEG", 
  forward:"third/3rd-12-b.JPEG", 
  backward:"third/3rd-13-f.JPEG", 
  left:"third/3rd-13-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-13-r.JPEG", 
  forward:"third/3rd-14-f.JPEG", 
  backward:null, 
  left:"third/3rd-13-f.JPEG", 
  right:"third/3rd-13-b.JPEG",
},
{
  image:"third/3rd-14-f.JPEG", 
  forward:"third/graphics-f.jpeg", 
  backward:"third/3rd-14-b.JPEG", 
  left:null, 
  right:"third/3rd-14-r.JPEG",
},
{
  image:"third/3rd-14-b.JPEG", 
  forward:"third/3rd-13-b.JPEG", 
  backward:"third/3rd-14-f.JPEG", 
  left:"third/3rd-14-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-14-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-14-f.JPEG", 
  right:"third/3rd-14-b.JPEG",
},
{
  image:"third/graphics-f.jpeg", 
  forward:"third/chelsea-b.JPEG", 
  backward:"third/3rd-15-b.JPEG", 
  left:null, 
  right:"third/3rd-15-r.JPEG",
},
{
  image:"third/3rd-15-b.JPEG", 
  forward:"third/3rd-14-b.JPEG", 
  backward:"third/graphics-f.jpeg", 
  left:"third/3rd-15-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-15-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/graphics-f.jpeg", 
  right:"third/3rd-15-b.JPEG",
},
{
  image:"third/3rd-16-f.JPEG", 
  forward:"third/3rd-17-f.JPEG", 
  backward:"third/3rd-16-b.JPEG", 
  left:null, 
  right:"third/3rd-16-r.JPEG",
},
{
  image:"third/3rd-16-b.JPEG", 
  forward:"third/chelsea-f.JPEG", 
  backward:"third/3rd-16-f.JPEG", 
  left:"third/3rd-16-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-16-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-16-f.JPEG", 
  right:"third/3rd-16-b.JPEG",
},
{
  image:"third/3rd-16-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-16-b.JPEG", 
  right:"third/3rd-16-f.JPEG",
},
{
  image:"third/3rd-17-f.JPEG", 
  forward:"third/3rd-18-f.JPEG", 
  backward:"third/3rd-17-b.JPEG", 
  left:null, 
  right:"third/3rd-17-r.JPEG",
},
{
  image:"third/3rd-17-b.JPEG", 
  forward:"third/3rd-16-b.JPEG", 
  backward:"third/3rd-17-f.JPEG", 
  left:"third/3rd-17-r.JPEG", 
  right:null,
},
{
  image:"third/3rd-17-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/3rd-17-f.JPEG", 
  right:"third/3rd-17-b.JPEG",
},

{
  image:"third/3rd-18-f.JPEG", 
  forward:"stairs/stairs-6-f.JPEG", 
  backward:"third/3rd-17-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"third/3rd-18-b.JPEG", 
  forward:"third/3rd-17-b.JPEG", 
  backward:"third/3rd-18-f.JPEG", 
  left:null, 
  right:null,
},

{
  image:"stairs/stairs-6-f.JPEG", 
  forward:"stairs/stairs-7-f.JPEG", 
  backward:"stairs/stairs-6-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-6-b.JPEG", 
  forward:"third/3rd-17-b.JPEG", 
  backward:"stairs/stairs-6-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-7-f.JPEG", 
  forward:null, 
  backward:null, 
  left:"stairs/stairs-7-r.JPEG", 
  right:"stairs/stairs-7-l.JPEG",
},
{
  image:"stairs/stairs-7-r.JPEG", 
  forward:"stairs/stairs-6-b.JPEG", 
  backward:"stairs/stairs-7-f.JPEG", 
  left:"stairs/stairs-7-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-7-l.JPEG", 
  forward:"stairs/stairs-8-f.JPEG", 
  backward:"stairs/stairs-7-f.JPEG", 
  left:null, 
  right:"stairs/stairs-7-r.JPEG",
},
{
  image:"stairs/stairs-8-f.JPEG", 
  forward:"second/2nd-4-f.JPEG", 
  backward:null, 
  left:"stairs/stairs-8-r.JPEG", 
  right:"stairs/stairs-8-l.JPEG",
},
{
  image:"stairs/stairs-8-l.JPEG", 
  forward:"stairs/stairs-9-l.JPEG", 
  backward:"stairs/stairs-8-f.JPEG", 
  left:null, 
  right:"stairs/stairs-8-r.JPEG",
},
{
  image:"stairs/stairs-8-r.JPEG", 
  forward:"stairs/stairs-7-f.JPEG", 
  backward:"stairs/stairs-8-f.JPEG", 
  left:"stairs/stairs-8-l.JPEG", 
  right:null,
},

{
  image:"stairs/stairs-9-r.JPEG", 
  forward:"stairs/stairs-8-f.JPEG", 
  backward:null, 
  left:"stairs/stairs-9-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-9-l.JPEG", 
  forward:"stairs/stairs-10-f.JPEG", 
  backward:null, 
  left:null, 
  right:"stairs/stairs-9-r.JPEG",
},
{
  image:"stairs/stairs-10-f.JPEG", 
  forward:"first/1-n-9-b.JPG", 
  backward:null, 
  left:"first/1-n-10-r.JPG", 
  right:"first/1-n-10-f.JPG",
},
{
  image:"stairs/stairs-11-f.JPEG", 
  forward:null, 
  backward:"stairs/stairs-11-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-11-b.JPEG", 
  forward:"stairs/stairs-10-f.JPEG", 
  backward:"stairs/stairs-11-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-4-f.JPEG", 
  forward:"second/2nd-5-f.JPEG", 
  backward:"second/2nd-4-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-4-b.JPEG", 
  forward:"stairs/stairs-8-r.JPEG", 
  backward:"second/2nd-4-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"second/2nd-5-f.JPEG", 
  forward:"second/2nd-6-f.JPEG", 
  backward:"second/2nd-5-b.JPEG", 
  left:"second/2nd-5-l.JPEG", 
  right:null,
},
{
  image:"second/2nd-5-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-5-b.JPEG", 
  right:"second/2nd-5-f.JPEG",
},
{
  image:"second/2nd-5-b.JPEG", 
  forward:"second/2nd-4-b.JPEG", 
  backward:"second/2nd-5-f.JPEG", 
  left:null, 
  right:"second/2nd-5-l.JPEG",
},
{
  image:"second/2nd-6-f.JPEG", 
  forward:"second/2nd-7-f.JPEG", 
  backward:"second/2nd-6-b.JPEG", 
  left:"second/2nd-6-l.JPEG", 
  right:null,
},
{
  image:"second/2nd-6-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-6-b.JPEG", 
  right:"second/2nd-6-f.JPEG",
},
{
  image:"second/2nd-6-b.JPEG", 
  forward:"second/2nd-5-b.JPEG", 
  backward:"second/2nd-6-f.JPEG", 
  left:null, 
  right:"second/2nd-6-l.JPEG",
},
{
  image:"second/2nd-7-f.JPEG", 
  forward:"second/2nd-8-f.JPEG", 
  backward:"second/2nd-7-b.JPEG", 
  left:"second/2nd-7-l.JPEG", 
  right:null,
},
{
  image:"second/2nd-7-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-7-b.JPEG", 
  right:"second/2nd-7-f.JPEG",
},
{
  image:"second/2nd-7-b.JPEG", 
  forward:"second/2nd-6-b.JPEG", 
  backward:"second/2nd-7-f.JPEG", 
  left:null, 
  right:"second/2nd-7-l.JPEG",
},
{
  image:"second/2nd-8-f.JPEG", 
  forward:"second/2nd-9-f.JPEG", 
  backward:"second/2nd-8-b.JPEG", 
  left:"second/2nd-8-l.JPEG", 
  right:null,
},
{
  image:"second/2nd-8-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-8-b.JPEG", 
  right:"second/2nd-8-f.JPEG",
},
{
  image:"second/2nd-8-b.JPEG", 
  forward:"second/2nd-7-b.JPEG", 
  backward:"second/2nd-8-f.JPEG", 
  left:null, 
  right:"second/2nd-8-l.JPEG",
},
{
  image:"second/2nd-9-f.JPEG", 
  forward:"second/2nd-10-f.JPEG", 
  backward:"second/2nd-9-b.JPEG", 
  left:"second/2nd-9-l.JPEG", 
  right:null,
},
{
  image:"second/2nd-9-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-9-b.JPEG", 
  right:"second/2nd-9-f.JPEG",
},
{
  image:"second/2nd-9-b.JPEG", 
  forward:"second/2nd-8-b.JPEG", 
  backward:"second/2nd-9-f.JPEG", 
  left:null, 
  right:"second/2nd-9-l.JPEG",
},
{
  image:"second/2nd-10-f.JPEG", 
  forward:"second/2nd-11-f.JPEG", 
  backward:"second/2nd-10-b.JPEG", 
  left:null, 
  right:"second/2nd-10-r.JPEG",
},
{
  image:"second/2nd-10-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-10-f.JPEG", 
  right:"second/2nd-10-b.JPEG",
},
{
  image:"second/2nd-10-b.JPEG", 
  forward:"second/2nd-9-b.JPEG", 
  backward:"second/2nd-10-f.JPEG", 
  left:"second/2nd-10-r.JPEG", 
  right:null,
},
{
  image:"second/2nd-11-f.JPEG", 
  forward:"second/2nd-12-f.JPEG", 
  backward:"second/2nd-11-b.JPEG", 
  left:"second/2nd-11-l.JPEG", 
  right:null,
},
{
  image:"second/2nd-11-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-11-b.JPEG", 
  right:"second/2nd-11-f.JPEG",
},
{
  image:"second/2nd-11-b.JPEG", 
  forward:"second/2nd-10-b.JPEG", 
  backward:"second/2nd-11-f.JPEG", 
  left:null, 
  right:"second/2nd-11-l.JPEG",
},
{
  image:"second/2nd-12-f.JPEG", 
  forward:"stairs/stairs-15-r.JPEG", 
  backward:"second/2nd-12-b.JPEG", 
  left:"second/2nd-12-l.JPEG", 
  right:"second/2nd-12-r.JPEG",
},
{
  image:"second/2nd-12-l.JPEG", 
  forward:null, 
  backward:"second/2nd-12-r.JPEG", 
  left:"second/2nd-12-b.JPEG", 
  right:"second/2nd-12-f.JPEG",
},
{
  image:"second/2nd-12-r.JPEG", 
  forward:"second/2nd-13-f.JPEG", 
  backward:"second/2nd-12-l.JPEG", 
  left:"second/2nd-12-f.JPEG", 
  right:"second/2nd-12-b.JPEG",
},
{
  image:"second/2nd-12-b.JPEG", 
  forward:"second/2nd-11-b.JPEG", 
  backward:"second/2nd-12-f.JPEG", 
  left:"second/2nd-12-r.JPEG", 
  right:"second/2nd-12-l.JPEG",
},
{
  image:"second/2nd-13-f.JPEG", 
  forward:"second/2nd-14-f.JPEG", 
  backward:"second/2nd-13-b.JPEG", 
  left:"second/2nd-13-l.JPEG", 
  right:"second/2nd-13-r.JPEG",
},
{
  image:"second/2nd-13-l.JPEG", 
  forward:null, 
  backward:"second/2nd-13-r.JPEG", 
  left:"second/2nd-13-b.JPEG", 
  right:"second/2nd-13-f.JPEG",
},
{
  image:"second/2nd-13-r.JPEG", 
  forward:null, 
  backward:"second/2nd-13-l.JPEG", 
  left:"second/2nd-13-f.JPEG", 
  right:"second/2nd-13-b.JPEG",
},
{
  image:"second/2nd-13-b.JPEG", 
  forward:"second/2nd-12-l.JPEG", 
  backward:"second/2nd-13-f.JPEG", 
  left:"second/2nd-13-r.JPEG", 
  right:"second/2nd-13-l.JPEG",
},
//position 14
{
  image:"second/2nd-14-f.JPEG", 
  forward:"second/2nd-15-f.JPEG", 
  backward:"second/2nd-14-b.JPEG", 
  left:"second/2nd-14-l.JPEG", 
  right:"second/2nd-14-r.JPEG",
},
{
  image:"second/2nd-14-l.JPEG", 
  forward:null, 
  backward:"second/2nd-14-r.JPEG", 
  left:"second/2nd-14-b.JPEG", 
  right:"second/2nd-14-f.JPEG",
},
{
  image:"second/2nd-14-r.JPEG", 
  forward:null, 
  backward:"second/2nd-14-l.JPEG", 
  left:"second/2nd-14-f.JPEG", 
  right:"second/2nd-14-b.JPEG",
},
{
  image:"second/2nd-14-b.JPEG", 
  forward:"second/2nd-13-b.JPEG", 
  backward:"second/2nd-14-f.JPEG", 
  left:"second/2nd-14-r.JPEG", 
  right:"second/2nd-14-l.JPEG",
},
//position 15
{
  image:"second/2nd-15-f.JPEG", 
  forward:null, 
  backward:"second/2nd-15-b.JPEG", 
  left:"second/2nd-15-l.JPEG", 
  right:"second/2nd-15-r.JPEG",
},
{
  image:"second/2nd-15-l.JPEG", 
  forward:"second/2nd-16-f.JPEG", 
  backward:"second/2nd-15-r.JPEG", 
  left:"second/2nd-15-b.JPEG", 
  right:"second/2nd-15-f.JPEG",
},
{
  image:"second/2nd-15-r.JPEG", 
  forward:"second/2nd-19-f.JPEG", 
  backward:"second/2nd-15-l.JPEG", 
  left:"second/2nd-15-f.JPEG", 
  right:"second/2nd-15-b.JPEG",
},
{
  image:"second/2nd-15-b.JPEG", 
  forward:"second/2nd-14-b.JPEG", 
  backward:"second/2nd-15-f.JPEG", 
  left:"second/2nd-15-r.JPEG", 
  right:"second/2nd-15-l.JPEG",
},
//position 16
{
  image:"second/2nd-16-f.JPEG", 
  forward:"second/2nd-17-f.JPEG", 
  backward:"second/2nd-16-b.JPEG", 
  left:null, 
  right:"second/2nd-16-r.JPEG",
},
{
  image:"second/2nd-16-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-16-f.JPEG", 
  right:"second/2nd-16-b.JPEG",
},
{
  image:"second/2nd-16-b.JPEG", 
  forward:"second/2nd-15-r.JPEG", 
  backward:"second/2nd-16-f.JPEG", 
  left:"second/2nd-16-r.JPEG", 
  right:null,
},
//position 17
{
  image:"second/2nd-17-f.JPEG", 
  forward:"second/2nd-18-f.JPEG", 
  backward:"second/2nd-17-b.JPEG", 
  left:null, 
  right:"second/2nd-17-r.JPEG",
},
{
  image:"second/2nd-17-r.JPEG", 
  forward:null, 
  backward:null, 
  left:"second/2nd-17-f.JPEG", 
  right:"second/2nd-17-b.JPEG",
},
{
  image:"second/2nd-17-b.JPEG", 
  forward:"second/2nd-16-b.JPEG", 
  backward:"second/2nd-17-f.JPEG", 
  left:"second/2nd-17-r.JPEG", 
  right:null,
},
//position 18
{
  image:"second/2nd-18-f.JPEG", 
  forward:null, 
  backward:"second/2nd-18-b.JPEG", 
  left:"second/2nd-18-l.JPEG", 
  right:"second/2nd-18-r.JPEG",
},
{
  image:"second/2nd-18-b.JPEG", 
  forward:"second/2nd-17-b.JPEG", 
  backward:"second/2nd-18-f.JPEG", 
  left:"second/2nd-18-r.JPEG", 
  right:"second/2nd-18-l.JPEG",
},
{
  image:"second/2nd-18-l.JPEG", 
  forward:null, 
  backward:"second/2nd-18-r.JPEG", 
  left:"second/2nd-17-b.JPEG", 
  right:"second/2nd-18-f.JPEG",
},
{
  image:"second/2nd-18-r.JPEG", 
  forward:null, 
  backward:"second/2nd-18-l.JPEG", 
  left:"second/2nd-18-f.JPEG", 
  right:"second/2nd-17-b.JPEG",
},
//position 19
//replace 15-l with 19-b when i can take the pictures
{
  image:"second/2nd-19-f.JPEG", 
  forward:"second/2nd-20-f.JPEG", 
  backward:"second/2nd-19-b.JPEG", 
  left:"second/2nd-19-l.JPEG", 
  right:"second/2nd-19-r.JPEG",
},
{
  image:"second/2nd-19-l.JPEG", 
  forward:"second/2nd-16-f.JPEG", 
  backward:"second/2nd-19-r.JPEG", 
  left:null, 
  right:"second/2nd-19-f.JPEG",
},
{
  image:"second/2nd-19-r.JPEG", 
  forward:null, 
  backward:"second/2nd-19-l.JPEG", 
  left:"second/2nd-19-f.JPEG", 
  right:"second/2nd-19-b.JPEG",
},
{
  image:"second/2nd-19-b.JPEG", 
  forward:"second/2nd-15-l.JPEG", 
  backward:"second/2nd-19-f.JPEG", 
  left:"second/2nd-19-r.JPEG", 
  right:"second/2nd-19-l.JPEG",
},
//position 19
//replace 15-l with 19-b when i can take the pictures
{
  image:"second/2nd-20-f.JPEG", 
  forward:"second/2nd-3-b.JPEG", 
  backward:"second/2nd-20-b.JPEG", 
  left:"second/2nd-20-l.JPEG", 
  right:"second/2nd-20-r.JPEG",
},
{
  image:"second/2nd-20-l.JPEG", 
  forward:"second/2nd-16-f.JPEG", 
  backward:"second/2nd-20-r.JPEG", 
  left:"second/2nd-20-b.JPEG", 
  right:"second/2nd-20-f.JPEG",
},
{
  image:"second/2nd-20-r.JPEG", 
  forward:null, 
  backward:"second/2nd-20-l.JPEG", 
  left:"second/2nd-20-f.JPEG", 
  right:"second/2nd-20-b.JPEG",
},
{
  image:"second/2nd-20-b.JPEG", 
  forward:"second/2nd-19-b.JPEG", 
  backward:"second/2nd-20-f.JPEG", 
  left:"second/2nd-20-r.JPEG", 
  right:"second/2nd-20-l.JPEG",
},

//back stairs

{
  image:"stairs/stairs-12-l.JPEG", 
  forward:"stairs/stairs-13-f.JPEG", 
  backward:"stairs/stairs-12-b.JPEG", 
  left:null, 
  right:"stairs/stairs-12-r.JPEG",
},
{
  image:"stairs/stairs-12-r.JPEG", 
  forward:"stairs/stairs-14-r.JPEG", 
  backward:"stairs/stairs-12-b.JPEG", 
  left:"stairs/stairs-12-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-12-b.JPEG", 
  forward:"first/1-n-6-b.jpeg", 
  backward:null, 
  left:"stairs/stairs-12-r.JPEG", 
  right:"stairs/stairs-12-l.JPEG",
},
{
  image:"stairs/stairs-13-f.JPEG", 
  forward:null, 
  backward:"stairs/stairs-13-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-13-b.JPEG", 
  forward:"stairs/stairs-12-b.JPEG", 
  backward:"stairs/stairs-13-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-14-r.JPEG", 
  forward:"stairs/stairs-15-f.JPEG", 
  backward:null, 
  left:"stairs/stairs-14-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-14-l.JPEG", 
  forward:"stairs/stairs-12-b.JPEG", 
  backward:null, 
  left:null, 
  right:"stairs/stairs-14-r.JPEG",
},
{
  image:"stairs/stairs-15-r.JPEG", 
  forward:"stairs/stairs-16-r.JPEG", 
  backward:"stairs/stairs-15-f.JPEG", 
  left:"stairs/stairs-15-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-15-l.JPEG", 
  forward:"stairs/stairs-14-l.JPEG", 
  backward:"stairs/stairs-15-f.JPEG", 
  left:null, 
  right:"stairs/stairs-15-r.JPEG",
},
{
  image:"stairs/stairs-15-f.JPEG", 
  forward:"second/2nd-12-b.JPEG", 
  backward:null, 
  left:"stairs/stairs-15-r.JPEG", 
  right:"stairs/stairs-15-l.JPEG",
},
{
  image:"stairs/stairs-16-r.JPEG", 
  forward:"stairs/stairs-17-f.JPEG", 
  backward:null, 
  left:"stairs/stairs-16-l.JPEG", 
  right:null,
},
{
  image:"stairs/stairs-16-l.JPEG", 
  forward:"stairs/stairs-15-f.JPEG", 
  backward:null, 
  left:null, 
  right:"stairs/stairs-15-r.JPEG",
},
{
  image:"stairs/stairs-17-f.JPEG", 
  forward:"third/3rd-12-f.JPEG", 
  backward:"stairs/stairs-17-b.JPEG", 
  left:null, 
  right:null,
},
{
  image:"stairs/stairs-17-b.JPEG", 
  forward:"stairs/stairs-16-l.JPEG", 
  backward:"stairs/stairs-17-f.JPEG", 
  left:null, 
  right:null,
},
{
  image:"third/chelsea-f.JPEG", 
  forward:"third/3rd-15-b.JPEG", 
  backward:"third/chelsea-b.JPEG", 
  left:"third/chelsea-l.JPEG", 
  right:null,
},
{
  image:"third/chelsea-l.JPEG", 
  forward:null, 
  backward:null, 
  left:"third/chelsea-b.JPEG", 
  right:"third/chelsea-f.JPEG",
},
{
  image:"third/chelsea-b.JPEG", 
  forward:"third/3rd-16-f.JPEG", 
  backward:"third/chelsea-f.JPEG", 
  left:null, 
  right:"third/chelsea-l.JPEG",
},
{
  image:"third/graphics-f.JPEG", 
  forward:"third/3rd-14-b.JPEG", 
  backward:"third/graphics-b.JPEG", 
  left:"third/3rd-15-r.JPEG", 
  right:null,
},

]


//108
//180
var index = 0;

//initialize image
function loadImage(){
  //add event listener to store button pressed
  
  //initialize image
  var img = document.createElement('img')
    img.src = images[index].image;
    document.getElementById('content').appendChild(img);
    //check buttons' on/off
    buttonOnOff()
    console.log(index)
    console.log(images[index].image)
}

//iterate image
function loadNextImage(){
  //grab button id and set new image to image held in that index location
  //create img variable to manipulate
  var img = document.getElementById('content').getElementsByTagName('img')[0]
  //replace old image with new
  img.src = images[index].image;
  //function to adjust buttons
  buttonOnOff();
  console.log(index)
  console.log(images[index].image)
}

//function to check and see if buttons should be enabled or disabled
function buttonOnOff(){
  if(images[index].forward !== null){
    document.getElementById('forward').disabled = false;
  }else{document.getElementById('forward').disabled = true;}
  if(images[index].backward !== null){
    document.getElementById('backward').disabled = false;
  }else{document.getElementById('backward').disabled = true;}
  if(images[index].left !== null){
    document.getElementById('left').disabled = false;
  }else{document.getElementById('left').disabled = true;}
  if(images[index].right !== null){
    document.getElementById('right').disabled = false;
  }else{document.getElementById('right').disabled = true;}

}


//add event listener for click to record button id
//change to else if? add case for wrong input 
function buttonID(direction){
    
  if(direction == 'forward'){
    newImage = images[index].forward
  }
  if(direction == 'backward'){
    newImage = images[index].backward
  }
  if(direction == 'left'){
    newImage = images[index].left
  }
  if(direction == 'right'){
    newImage = images[index].right
  }

  //update image based off direction picked
  index = images.findIndex(Object => {return Object.image == newImage});
}



document.onkeydown = function(e) {
 //maybe add to if statements?
  e.preventDefault(); 
if(e.key=='ArrowUp'){
  
  document.getElementById('forward').click();
}
else if(e.key=='ArrowDown'){
  document.getElementById('backward').click();
}
else if(e.key=='ArrowLeft'){
  document.getElementById('left').click();
}
else if(e.key=='ArrowRight'){
  document.getElementById('right').click();
}
else if(e.key=='w'){
  document.getElementById('forward').click();
}
else if(e.key=='s'){
  document.getElementById('backward').click();
}
else if(e.key=='a'){
  document.getElementById('left').click();
}
else if(e.key=='d'){
  document.getElementById('right').click();
}

  
};





